#!/usr/bin/env bash

EPMH_PLUGIN_NAME="esync"
EPMH_PLUGIN_INFO="Включить поддержку esync. Повышает производительность
многих игр, особенно тех, которые в значительной степени
зависят от многопоточности. (значение взято из SteamOS)"

epmh_check () {
    [ -e /etc/security/limits.d/99-esync.conf ] && return 0 || return 1
}

epmh_function () {
    cat << EOF >> /etc/security/limits.d/99-esync.conf
*		soft	nofile	1024
*		hard	nofile	524288
EOF
[ "$?" == 0 ] && return 0 || return 1
}
